FROM node:20-alpine 

WORKDIR /app

COPY ./package*.json  ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm install typescript

RUN npm run build

EXPOSE 4001

CMD ["node", "dist/index.js"]
